[package]
name = "genetic-algorithm-traits"
version = "0.1.0"
edition = "2021"
authors = ["Tim Toebrock"]
license = "MIT"
description = """
Traits that can be used to implement genetic-algorithms for a specific domain.
"""

[profile.dev]
opt-level = 3
